routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CarController;
use App\Http\Controllers\AdminController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('search');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/users', [AdminController::class, 'index'])->middleware('admin');

Route::get('/changePassword', [AdminController::class, 'changePasswordForm'])->name('changePassword');
Route::post('/changePassword',[AdminController::class, 'changePassword'])->name('changePassword');

Route::get('/editUser', [AdminController::class, 'editUserForm'])->name('editUser');
Route::post('/updateUser', [AdminController::class, 'updateUser'])->name('updateUser');

Route::delete('/deleteUser/{user}',[AdminController::class, 'deleteUser'])->middleware('admin');

Route::get('/mycars', [CarController::class, 'mycars'])->name('mycars')->middleware('user');

Route::get('/destroypicture/{image}',[CarController::class, 'destroyPicture'])->name('destroypicture')->middleware('user');
Route::get('/search',[CarController::class, 'process'])->name('search');

Route::get('cart', [CarController::class, 'cart']);
Route::get('add-to-cart/{car}', [CarController::class ,'addToCart']);
Route::patch('update-cart', [CarController::class, 'updateCart']); 
Route::delete('remove-from-cart', [CarController::class, 'remove']);

Route::resource('cars', CarController::class);

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    use HasFactory;

    protected $fillable=['brand','year','price','gearbox','emissions','service','information','user_id'];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }
    
    public function carphotos()
    {
        return $this->hasMany('App\Models\CarPhoto');
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Models\Car;
use App\Models\CarPhoto;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;
use App\Http\Requests\UploadRequest;
use App\Http\Requests\UpdateRequest;

class CarController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth')->except(['process','show','cart','addToCart','updateCart','remove']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cars = Car::with('user')->get();
        return view('cars.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cars.create'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UploadRequest $request)
    {
        $car = Car::create($request->all());
        //$car = new Car();
        //$car->brand = $request->brand;
        //$car->price =$request->price;
        //$car->user_id = \Auth::id();
        $car->save();

        if($request->hasFile('images')){
            $this->storeimages($car, $request->images);
        }
        
        return redirect('/mycars');
    }

    protected function storeimages($car, $images)
    {       
        foreach($images as $image){
            $ext = $image->getClientOriginalExtension();
            $filename = date('YmdHis').rand(1,99999).'.'.$ext;            
            $filepath = $image->storeAs('public/images',$filename);

            CarPhoto::create([
                'car_id' => $car->id,
                'image' => $filename
            ]);
        }        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        return view('cars.show',  compact('car'));
    }

    public function mycars(){
        $cars = Car::where('user_id', auth()->user()->id)->paginate(2);
        return view('cars.mycars', compact('cars'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
        return view('cars.edit', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroyPicture($id)
    {        
        $carphoto = CarPhoto::find($id);        
        Storage::delete('public/images/'.$carphoto->image);       
        $carphoto->delete();        
        return \Redirect::back()->with('carphoto', $carphoto);
    } 


    public function update(UpdateRequest $request, Car $car)
    {
        $car->brand = $request->brand;
        $car->year = $request->year;
        $car->price = $request->price;
        $car->gearbox = $request->gearbox;
        $car->emissions = $request->emissions;
        $car->service = $request->service;
        $car->information = $request->information;
        $car->save();

        if($request->hasFile('images')){
            $this->storeimages($car, $request->images);
        }
        
        return redirect('/mycars')->withMessage ('Success','Car has been updated!');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        foreach( $car->carphotos as $carphoto ){
            Storage::delete('public/images/'.$carphoto->image);
        }

        $car->delete();

        return redirect('/mycars')->withMessage ('Success','Car has been deleted!');
    }


    public function process(Request $request)
    {
        $brand = $request->query('brand', "");
        //dd($brand);
        $words = explode(" ", $brand);

        $startyear = $request->query('startyear');       
        $endyear = $request->query('endyear');  

        $startprice = $request->query('startprice',0);
        $endprice = $request->query('endprice',99999);

        $gearbox = $request->query('gearbox');
        $emissions = $request->query('emissions');
        $service = $request->query('service');
        
        $query = Car::where('id', '>', 0);

        foreach($words as $word){
            $query->where('brand','like',"%$word%");
        }

        if ($startyear && $endyear){
            $query->whereBetween('year', [$startyear, $endyear]);
        }

        if($startprice && $endprice){
            $query->whereBetween('price', [$startprice, $endprice]);
        }    
               
        if($gearbox){
            $query->where('gearbox','like',"%$gearbox%");
        }

        if($emissions){
            $query->where('emissions','like',"%$emissions%");
        }

        if($service){
            $query->where('service','like',"%$service%");
        }

                
        if('asc' == $request->query('fetchval')){
            $query->orderBy('price', 'ASC');
        }
        
        if('desc' == $request->query('fetchval')){
            $query->orderBy('price','DESC');
        }

        if('newest' == $request->query('fetchval')){
            $query->orderBy('created_at','DESC');
        }

        if('oldest' == $request->query('fetchval')){
            $query->orderBy('created_at','ASC');
        } 

        $cars = $query->paginate(2);    
        //dd($cars);
        return view('search', compact('cars'));
    }


    public function cart()
    {
        return view('cart');
    }


    public function addToCart($id)
    {
        $car = Car::find($id);
 
        if(!$car){ 
            abort(404); 
        }
 
        $cart = session()->get('cart');
 
        // if cart is empty then this the first product
        if(!$cart) {
 
            $cart = [
                    $id => [
                        "brand" => $car->brand,
                        "quantity" => 1,
                        "price" => $car->price                        
                    ]
            ];
 
            session()->put('cart', $cart);
 
            return redirect()->back()->with('success', 'Car added to cart successfully!');
        }
 
        // if cart not empty then check if this product exist then increment quantity
        if(isset($cart[$id])){ 
            $cart[$id]['quantity']++; 
            session()->put('cart', $cart); 
            return redirect()->back()->with('success', 'Car added to cart successfully!');
 
        }
 
        // if item not exist in cart then add to cart with quantity = 1
        $cart[$id] = [
            "brand" => $car->brand,
            "quantity" => 1,
            "price" => $car->price            
        ];
 
        session()->put('cart', $cart);
 
        return redirect()->back()->with('success', 'Car added to cart successfully!');    
    }


    public function updateCart(Request $request)
    {
        if($request->id && $request->quantity){        
            $cart = session()->get('cart'); 
            $cart[$request->id]["quantity"] = $request->quantity; 
            session()->put('cart', $cart); 
            session()->flash('success', 'Cart updated successfully');
        }
    }
    

    public function remove(Request $request)
    {
        if($request->id){ 
            $cart = session()->get('cart'); 
            if(isset($cart[$request->id])){ 
                unset($cart[$request->id]); 
                session()->put('cart', $cart);
            } 
            session()->flash('success', 'Car removed successfully');
        }
    }
}

resources/views/cars/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container table-responsive">
    <h1>Add Car</h1>
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>	    	
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>    
    @endif
    <form method="POST" action="{{route('cars.store')}}" class="text-center border border-light p-5" enctype="multipart/form-data">
        @csrf
        <table class="table table-bordered">
            <tr>
               <td><label for="brand">Car Brand</label></td>
               <td><input type="text" name="brand" value="{{old('price')}}"></td>     
            </tr>
            <tr>
            <td><label for="year">Car Year</label></td>
                <td>
                    <select name="year" id="year" value="{{old('year')}}" >
                        <option value="{{old('year')}}" selected="selected">{{old('year')}}</option>                        
                                
                                @for ($year=date('Y'); $year>=1960; $year--)                                
                                    <option value="{{ $year }}">{{ $year }}</option>
                                @endfor   
                            
                    </select>    
                </td>          
            </tr>
            <tr>
                <td><label for="price">Car Price</label></td>
                <td><input type="number" name="price" value="{{old('price')}}"></td>
            </tr>
            <tr>
                <td><label for="gearbox">Car Gearbox</label></td>
                <td>    
                    <input type="radio" name="gearbox" id="gearbox" class ="mr-1" value='Manual'@if (old('gearbox') == 'Manual') checked @endif >Manual
                    <input type="radio" name="gearbox" id="gearbox" class ="mr-1" value='Automatic'@if (old('gearbox') == 'Automatic') checked @endif >Automatic
                </td>            
            </tr>
            <tr>
                <td><label for="emissions" class="col-md-4 col-form-label">Emissions Class</label></td>
                <td>
                    <select name="emissions" id="emissions">
                    <option value="{{old('emissions')}}" selected="selected">{{old('emissions')}}</option>
                                            <option value="Euro1">Euro1</option>
                                            <option value="Euro2">Euro2</option>
                                            <option value="Euro3">Euro3</option>
                                            <option value="Euro4">Euro4</option>
                                            <option value="Euro5">Euro5</option>
                                            <option value="Euro6">Euro6</option>
                    </select>
                </td>          
            </tr>
            <tr>
                <td><label for="service" class="col-form-label">Service Manual</label></td>
                <td><input type="checkbox" name="service" id="service" value='service' @if (old('service') == 'service') checked @endif></td>
            </tr>
            <tr>
                <td><label for="information">Other Information</label></td>
                <td><textarea name="information" id="information" rows="5" class="form-control" placeholder="(other information)"></textarea></td>
            </tr>
            <tr>
                <td><label for="images">Select Images</label></td> 
                <td><input type="file" name="images[]" id="images" multiple="multiple"></td>
                           
            </tr>
            <tr>
                <td colspan="2">
                    <input type="hidden" name="user_id" value="{{Auth::id()}}">
                    <input type="submit" class="btn btn-primary" value="Add Car">
                </td>    
            </tr>            
        </table>    
    </form>
</div>        
@endsection

resources/views/cars/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container table-responsive">
    <h1>Edit Car</h1>
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>	    	
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>    
    @endif
    <form method="POST" action="{{route('cars.update',$car->id)}}" class="text-center border border-light p-5" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <table class="table">
            <tr>
               <td><label for="brand">Car Brand</label></td>
               <td><input type="text" name="brand" value="{{ $car->brand }}"></td>     
            </tr>
            <tr>
                <td><label for="year">Car Year</label></td>
                <td>
                    <select name="year" id="year" value="{{old('year')}}" >
                        <option value="{{ $car->year }}" selected="selected">{{ $car->year }}</option>                        
                                
                                @for ($year=date('Y'); $year>=1960; $year--)                                
                                    <option value="{{ $year }}">{{ $year }}</option>
                                @endfor   
                            
                    </select>    
                </td>          
            </tr>
            <tr>
                <td><label for="price">Car Price</label></td>
                <td><input type="number" name="price" value="{{ $car->price }}"></td>
            </tr>
            <tr>
                <td><label for="gearbox">Car Gearbox</label></td>
                <td>    
                    <input type="radio" name="gearbox" id="gearbox" class ="mr-1" value='Manual'@if ($car->gearbox == 'Manual') checked @endif >Manual
                    <input type="radio" name="gearbox" id="gearbox" class ="mr-1" value='Automatic'@if ($car->gearbox == 'Automatic') checked @endif >Automatic
                </td>            
            </tr>
            <tr>
                <td><label for="emissions" class="col-md-4 col-form-label">Emissions Class</label></td>
                <td>
                    <select name="emissions" id="emissions">
                    <option value="{{ $car->emissions }}" selected="selected">{{ $car->emissions }}</option>
                                            <option value="Euro1">Euro1</option>
                                            <option value="Euro2">Euro2</option>
                                            <option value="Euro3">Euro3</option>
                                            <option value="Euro4">Euro4</option>
                                            <option value="Euro5">Euro5</option>
                                            <option value="Euro6">Euro6</option>
                    </select>
                </td>          
            </tr>
            <tr>
                <td><label for="service" class="col-form-label">Service Manual</label></td>
                <td><input type="checkbox" name="service" id="service" value='service' @if ($car->service == 'service') checked @endif></td>
            </tr>
            <tr>
                <td><label for="information">Other Information</label></td>
                <td><textarea name="information" id="information" rows="5" class="form-control">{{ $car->information }}</textarea></td>
            </tr>
            <tr>                
                @foreach( $car->carphotos as $carphoto )
                    <td>            
                        <img src="{{asset('storage/images/'.$carphoto->image)}}" width="100">             
                        <br><br>
                        <a href="/destroypicture/{{ $carphoto->id }}" class="btn btn-danger" onclick="return confirm('Are you sure to delete this picture?');">Delete</a>
                    </td>
                @endforeach            
            </tr>
            <tr>
                <td><label for="images">Select Images</label></td>
                <td><input type="file" name="images[]" id="images" multiple="multiple"></td>                            
            </tr>
            <tr>
                <td colspan="2">                    
                   <input type="submit" class="btn btn-primary" value="Update Car">
                </td>    
            </tr>            
        </table>    
    </form>
</div>        
@endsection

resources/views/cars/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container table-reponsive">
    <h1>Show Cars</h1>    
    <table class="table">
        <thead>
           <tr>
               <th class="text-center">Car Brand</th>
               <th class="text-center">Car Price</th>
               <th class="text-center">Car Images</th>
               <th class="text-center">User Info</th>
               <th class="text-center">Actions</th>
          </tr>         
        </thead>
        <tbody>
            @foreach($cars as $car)
                <tr>
                    <td class="text-center">{{ $car->brand }}</td>
                    <td class="text-center">{{ $car->price }}</td>
                    <td align="center">
                        <div id="carouselExampleControls" class="carousel slide" data-interval="false" data-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                @foreach( $car->carphotos as $carphoto )    
                                    <div class="carousel-item {{ $loop->first ? 'active' : '' }}">
                                        <img class="d-block img-fluid" src="{{ asset('storage/images/'.$carphoto->image) }}" width="200">             
                                    </div>
                                @endforeach                                
                            </div>
                        </div>
                    </td>
                    <td class="text-center">{{ $car->user->email }}</td>
                    <td class="text-center">                        
                        <form method="POST" action="{{ route('cars.destroy', $car->id) }}">
                            @csrf
                            @method('delete')
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>    
                    </td>
                </tr>
            @endforeach
        </tbody>        
    </table>
</div>           
@endsection

resources/views/cars/mycars.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Show MyCars</h1>
    <a href="{{route('cars.create')}}" class="btn btn-primary">Create Car</a>
    <br><br>        
        <table class="table table-stripped table-bordered table-hover">
            <thead class="thead-dark">
            <tr>
                <th class="text-center">Car Id</th>
                <th class="text-center">Car Brand</th>
                <th class="text-center">Car Price</th>
                <th class="text-center">Car Pictures</th>
                <th class="text-center">User Email</th>
                <th class="text-center">Actions</th>
            </tr>         
            </thead>
            <tbody>
                @foreach($cars as $car)
                <tr>
                    <td class="text-center">{{ $car->id }}</td>
                    <td class="text-center">{{ $car->brand }}</td>
                    <td class="text-center">{{ $car->price }}</td>
                    <td align="center">
                        <div id="carouselExampleControls" class="carousel slide" data-interval="false" data-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                @foreach( $car->carphotos as $carphoto )    
                                    <div class="carousel-item {{ $loop->first ? 'active' : '' }}">
                                        <img class="d-block img-fluid" src="{{ asset('storage/images/'.$carphoto->image) }}" width="200">             
                                    </div>
                                @endforeach                                
                            </div>
                        </div>
                    </td>
                    <td class="text-center">{{ $car->user->email }}</td>
                    <td class="text-center">
                        <a href="{{ route('cars.show', $car->id) }}" class="btn btn-info">Show</a>
                        <br><br>
                        <a href="{{ route('cars.edit', $car->id) }}" class="btn btn-warning">Edit</a>
                        <br><br>
                        <form method="POST" action="{{ route('cars.destroy', $car->id) }}">
                            @csrf
                            @method('delete')
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>       
                    </td>
                </tr>
                @endforeach
            </tbody>        
        </table>
        <div class="pagination-block">
            {{ $cars->appends(request()->input())->links('layouts.paginationlinks') }}
        </div>   
</div>           
@endsection

resources/views/cars/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
<h1 align="left">Show Car</h1>    
<br><br>    
        <table class="table table-bordered">
            <tr>
                <td colspan="8" align="center">
                    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            @foreach( $car->carphotos as $carphoto )
                                <li data-target="#carouselExampleCaptions" data-slide-to="{{$loop->index}}" class="{{ $loop->first ? 'active' : '' }}"></li>
                            @endforeach
                        </ol> 
                        <div class="carousel-inner">
                            <div class="carousel-inner" role="listbox">
                                @foreach( $car->carphotos as $carphoto )    
                                    <div class="carousel-item {{ $loop->iteration == 1 ? 'active' : '' }}">
                                        <img class="d-block img-fluid" src="{{asset('storage/images/'.$carphoto->image)}}" width="600">             
                                    </div>
                                @endforeach
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div> 
                </td>        
            </tr>            
            <tr>    
                <th class="text-center">Car Brand</th>
                <td class="text-center" >{{ $car->brand }}</td>
            </tr>
            <tr>    
                <th class="text-center">Car Year</th>
                <td class="text-center">{{ $car->year }}</td>
            </tr>
            <tr>    
                <th class="text-center">Car Price</th>
                <td class="text-center">{{ $car->price }}</td>
            </tr>
            <tr>    
                <th class="text-center">Car Gearbox</th>
                 <td class="text-center">{{ $car->gearbox }}</td>
            </tr>
            <tr>     
                <th class="text-center" >Car Emissions</th>
                 <td class="text-center" >{{ $car->emissions }}</td>
            </tr>
            <tr>             
                <th class="text-center" >Car Service</th>
                <td class="text-center">{{ $car->service }}</td>
            </tr>
            <tr>            
                <th class="text-center">Car Information</th>
                <td class="text-center">{{ $car->information }}</td>                      
            </tr>
        </table>
</div>
@endsection